#ifndef CONSTANTS_H
#define CONSTANTS_H

#define BUFFER_SIZE 150
#define MINIMUM_FOR_DOLLARS 100
#define DIGIT_SEPERATOR 10
#define DOUBLE_DIGIT_SEPERATOR 100
#define THOUSAND_MULTIPLE_SEPERATOR 1000
#define CHECK_IF_TEENS 2
#define TEEN_INDEX_OFFSET 10

#endif